name: CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"
      - run: npm install
      - run: npm run dtslint
      - name: Delete old package, if available
        continue-on-error: true
        uses: actions/delete-package-versions@v1
          with:
            package-name: "@${{ github.repository }}" 
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}