name: CD
on:
  push:
    branches: [ main, 'tjarbo/CD-fix' ]
#    paths:
#      - '**.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Prepare git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"
      - run: npm install
      - run: npm run dtslint
      - run: npm version minor
      - name: Commit new version 
        run: |
          git commit -am "🔖 Released new version"
          git push
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          