name: CD
on:
  push:
    branches: [ main ]
    paths:
      - '**.ts'

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"
      - run: npm install
      - run: npm run dtslint
      - run: npm version minor
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}